version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - ./msyql/:/var/lib/mysql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  myapp:
    tty: true
    image: 'php71-apache'
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    ports:
      - 8090:80
    volumes:
      - ./app:/var/www/webapp
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./php.ini:/etc/php/7.1/apache2/php.ini
