version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password
    volumes:
      - ./db:/bitnami/mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  myapp:
    tty: true
    build: .
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    ports:
      - 8090:80
    volumes:
      - ./app:/var/www/webapp
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php-dev.ini:/usr/local/etc/php/php.ini
